// frontend/src/components/vnic/VCNPanel.vue
<script setup lang="ts">
defineOptions({ name: 'VCNPanel' })

import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import request from '../../utils/request'
import type { VcnInfo } from '../../types/api'
import ConfigureIPv6Modal from './ConfigureIPv6Modal.vue'
import ReassignIPModal from './ReassignIPModal.vue'

const props = defineProps<{ instanceId: string; instanceDbId: number; compartmentId: string; tenantId: number; currentPublicIp?: string }>()

const loading = ref(false)
const vcnList = ref<VcnInfo[]>([])
const selectedVcn = ref<VcnInfo | null>(null)
const currentPublicIp = ref('')

// Modals
const configureIpv6Visible = ref(false)
const reassignIpVisible = ref(false)

async function loadVcns() {
  loading.value = true
  try {
    const res = await request.get('/oci/vcn/list', { params: { tenantId: props.tenantId, compartmentId: props.compartmentId } }) as VcnInfo[]
    vcnList.value = res ?? []
  } catch (e: any) {
    ElMessage.error(e.message || '加载 VCN 列表失败')
  } finally {
    loading.value = false
  }
}

function selectVcn(vcn: VcnInfo) {
  selectedVcn.value = vcn
}

onMounted(() => {
  currentPublicIp.value = props.currentPublicIp ?? ''
  loadVcns()
})
</script>

<template>
  <div class="vcn-panel" v-loading="loading">
    <!-- VCN List -->
    <el-card shadow="hover" style="margin-bottom: 16px;">
      <template #header>VCN 列表</template>
      <el-table :data="vcnList" stripe highlight-current-row @current-change="selectVcn">
        <el-table-column prop="displayName" label="名称" />
        <el-table-column prop="cidrBlock" label="CIDR" />
        <el-table-column prop="dnsLabel" label="DNS 标签" />
        <el-table-column prop="timeCreated" label="创建时间" width="180" />
      </el-table>
      <el-empty v-if="vcnList.length === 0" description="暂无 VCN" />
    </el-card>

    <!-- VCN Detail -->
    <el-card v-if="selectedVcn" shadow="hover" style="margin-bottom: 16px;">
      <template #header>VCN 详情: {{ selectedVcn.displayName }}</template>
      <el-descriptions :column="2" border>
        <el-descriptions-item label="OCID"><el-text truncated>{{ selectedVcn.id }}</el-text></el-descriptions-item>
        <el-descriptions-item label="CIDR">{{ selectedVcn.cidrBlock }}</el-descriptions-item>
        <el-descriptions-item label="DNS 标签">{{ selectedVcn.dnsLabel || '-' }}</el-descriptions-item>
        <el-descriptions-item label="创建时间">{{ selectedVcn.timeCreated }}</el-descriptions-item>
      </el-descriptions>
      <el-space style="margin-top: 12px;">
        <el-button @click="configureIpv6Visible = true">配置 IPv6 安全规则</el-button>
      </el-space>
    </el-card>

    <!-- Public IP -->
    <el-card shadow="hover">
      <template #header>公网 IP 管理</template>
      <div style="display: flex; align-items: center; gap: 16px;">
        <span>当前公网 IP: <strong>{{ currentPublicIp || '无' }}</strong></span>
        <el-button type="warning" @click="reassignIpVisible = true">重新分配公网 IP</el-button>
      </div>
    </el-card>

    <!-- Modals -->
    <ConfigureIPv6Modal v-model="configureIpv6Visible" :vcn-id="selectedVcn?.id ?? ''" :tenant-id="tenantId" @saved="loadVcns" />
    <ReassignIPModal v-model="reassignIpVisible" :instance-id="instanceId" :instance-db-id="instanceDbId" @saved="(ip) => currentPublicIp = ip" />
  </div>
</template>

<style scoped>
.vcn-panel {
  padding: var(--space-4);
}
</style>

// frontend/src/pages/vnic/tabs/VcnPanel.tsx
import { useCallback, useEffect, useState } from 'react'
import { Table, Button, Card, Descriptions, message } from 'antd'
import { vcnList, vcnConfigureIpv6, vnicReassignIp } from '@/api/vnic'
import type { VcnInfo } from '@/types/api'

interface Props {
  tenantId: number
  compartmentId: string
  instanceId: string
  instanceDbId: number
  currentPublicIp: string
}

export default function VcnPanel({ tenantId, compartmentId, instanceId, instanceDbId, currentPublicIp }: Props) {
  const [loading, setLoading] = useState(false)
  const [vcnList2, setVcnList] = useState<VcnInfo[]>([])
  const [selectedVcn, setSelectedVcn] = useState<VcnInfo | null>(null)
  const [publicIp, setPublicIp] = useState(currentPublicIp)
  const [reassigning, setReassigning] = useState(false)

  const loadVcns = useCallback(async () => {
    if (!compartmentId || !tenantId) return
    setLoading(true)
    try {
      const data = await vcnList(tenantId, compartmentId)
      setVcnList(data || [])
    } catch (e: unknown) {
      message.error((e as Error).message)
    } finally {
      setLoading(false)
    }
  }, [tenantId, compartmentId])

  useEffect(() => { loadVcns() }, []) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { setPublicIp(currentPublicIp) }, [currentPublicIp])

  async function handleConfigureIpv6() {
    if (!selectedVcn) return
    try {
      await vcnConfigureIpv6(tenantId, selectedVcn.id)
      message.success('IPv6 安全规则配置成功')
    } catch (e: unknown) {
      message.error((e as Error).message)
    }
  }

  async function handleReassignIp() {
    setReassigning(true)
    try {
      const res = await vnicReassignIp(instanceId, instanceDbId)
      if (res.publicIp) {
        setPublicIp(res.publicIp)
        message.success(`公网 IP 已重新分配: ${res.publicIp}`)
      }
    } catch (e: unknown) {
      message.error((e as Error).message)
    } finally {
      setReassigning(false)
    }
  }

  return (
    <div className="p-4 space-y-4">
      {/* VCN List */}
      <Card title="VCN 列表" size="small">
        <Table
          dataSource={vcnList2}
          loading={loading}
          rowKey="id"
          size="small"
          onRow={(record) => ({ onClick: () => setSelectedVcn(record) })}
          rowClassName={(record) => record.id === selectedVcn?.id ? 'bg-blue-50' : ''}
          pagination={false}
        >
          <Table.Column title="名称" dataIndex="displayName" />
          <Table.Column title="CIDR" dataIndex="cidrBlock" />
          <Table.Column title="DNS 标签" dataIndex="dnsLabel" />
          <Table.Column title="创建时间" dataIndex="timeCreated" width={180} />
        </Table>
      </Card>

      {/* VCN Detail */}
      {selectedVcn && (
        <Card title={`VCN 详情: ${selectedVcn.displayName}`} size="small">
          <Descriptions column={2} size="small" bordered>
            <Descriptions.Item label="OCID"><span className="font-mono text-xs truncate block max-w-[300px]">{selectedVcn.id}</span></Descriptions.Item>
            <Descriptions.Item label="CIDR">{selectedVcn.cidrBlock}</Descriptions.Item>
            <Descriptions.Item label="DNS 标签">{selectedVcn.dnsLabel || '-'}</Descriptions.Item>
            <Descriptions.Item label="创建时间">{selectedVcn.timeCreated}</Descriptions.Item>
          </Descriptions>
          <Button className="mt-3" onClick={handleConfigureIpv6}>配置 IPv6 安全规则</Button>
        </Card>
      )}

      {/* Public IP */}
      <Card title="公网 IP 管理" size="small">
        <div className="flex items-center gap-4">
          <span>当前公网 IP: <strong>{publicIp || '无'}</strong></span>
          <Button type="primary" danger loading={reassigning} onClick={handleReassignIp}>重新分配公网 IP</Button>
        </div>
      </Card>
    </div>
  )
}
