// frontend/src/pages/Dashboard.tsx
import { useCallback, useEffect, useState } from 'react'
import { Card, Col, Row, Statistic, Typography, Button, Space, Tag } from 'antd'
import {
  ApiOutlined,
  TeamOutlined,
  CheckCircleOutlined,
  SafetyOutlined,
  CopyOutlined,
  ReloadOutlined,
  RocketOutlined,
  DesktopOutlined,
  SettingOutlined,
  LinkOutlined,
} from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import client from '@/api/client'
import type { DashboardStats, EngineStatus, MessageChannels, SystemConfig } from '@/types/api'

const { Title, Text } = Typography

export default function Dashboard() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const [stats, setStats] = useState<DashboardStats | null>(null)
  const [engine, setEngine] = useState<EngineStatus | null>(null)
  const [channels, setChannels] = useState<MessageChannels | null>(null)
  const [sysConfig, setSysConfig] = useState<SystemConfig | null>(null)
  const [loading, setLoading] = useState(false)

  const loadAll = useCallback(async () => {
    setLoading(true)
    await Promise.all([
      client.get('/api/stats').then((d) => setStats(d as DashboardStats)).catch(() => {}),
      client.get('/boot/systemStatus').then((d) => setEngine(d as EngineStatus)).catch(() => {}),
      client.get('/api/config/message-enabled').then((d) => setChannels(d as MessageChannels)).catch(() => {}),
      client.get('/system/config').then((d) => setSysConfig(d as SystemConfig)).catch(() => {}),
    ])
    setLoading(false)
  }, [])

  useEffect(() => {
    loadAll()
  }, [loadAll])

  const engineRunning = (engine?.parentActive ?? 0) > 0 || (engine?.registeredJobs ?? 0) > 0
  const onlineRate = stats?.instanceCount
    ? Math.round(((stats.onlineCount ?? 0) / stats.instanceCount) * 100)
    : 0

  const quickLinks = [
    { label: '抢机任务', icon: <RocketOutlined />, path: '/boot' },
    { label: '实例列表', icon: <DesktopOutlined />, path: '/instances' },
    { label: '租户管理', icon: <TeamOutlined />, path: '/tenants' },
    { label: '系统设置', icon: <SettingOutlined />, path: '/settings' },
  ]

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <Title level={4} className="!mb-0">{t('dashboard.welcome')}</Title>
        <Button icon={<ReloadOutlined />} loading={loading} onClick={loadAll}>
          {t('common.refresh')}
        </Button>
      </div>

      {/* ── Stat cards ─────────────────────────────────────── */}
      <Row gutter={[16, 16]}>
        <Col xs={24} sm={12} lg={6}>
          <Card hoverable onClick={() => navigate('/instances')}>
            <Statistic
              title="在线实例"
              value={stats?.onlineCount ?? 0}
              suffix={stats?.instanceCount ? `/ ${stats.instanceCount}` : undefined}
              prefix={<CheckCircleOutlined />}
              valueStyle={{ color: '#52c41a' }}
            />
            <Text type="secondary" className="text-xs">{onlineRate}% 在线率</Text>
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card hoverable onClick={() => navigate('/tenants')}>
            <Statistic
              title={t('dashboard.tenantCount')}
              value={stats?.tenantCount ?? 0}
              prefix={<TeamOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card hoverable onClick={() => navigate('/boot')}>
            <Statistic
              title="抢机引擎"
              value={engine?.runningTasks ?? 0}
              suffix={`/ ${engine?.totalTasks ?? 0}`}
              prefix={<RocketOutlined />}
              valueStyle={{ color: engineRunning ? '#52c41a' : '#ff4d4f' }}
            />
            <Tag color={engineRunning ? 'success' : 'error'} className="mt-1">
              {engineRunning ? '运行中' : '已停止'}
            </Tag>
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card hoverable>
            <Statistic
              title={t('dashboard.backupCount')}
              value={stats?.backupCount ?? 0}
              prefix={<CopyOutlined />}
            />
          </Card>
        </Col>
      </Row>

      {/* ── Second row: channels + system info ─────────────── */}
      <Row gutter={[16, 16]} className="mt-4">
        <Col xs={24} lg={12}>
          <Card
            title={<><ApiOutlined className="mr-2" />通知渠道</>}
            size="small"
          >
            {channels ? (
              <div className="flex flex-col gap-2">
                {[
                  { key: 'telegram' as const, label: 'Telegram' },
                  { key: 'dingtalk' as const, label: '钉钉' },
                  { key: 'bark' as const, label: 'Bark' },
                  { key: 'feishu' as const, label: '飞书' },
                ].map((ch) => (
                  <div key={ch.key} className="flex items-center justify-between px-2 py-1 rounded hover:bg-gray-50">
                    <Text>{ch.label}</Text>
                    <Tag color={channels[ch.key] ? 'success' : 'default'}>
                      {channels[ch.key] ? '已配置' : '未配置'}
                    </Tag>
                  </div>
                ))}
              </div>
            ) : (
              <Text type="secondary">{t('common.noData')}</Text>
            )}
          </Card>
        </Col>

        <Col xs={24} lg={12}>
          <Card
            title={<><SafetyOutlined className="mr-2" />系统概览</>}
            size="small"
          >
            <div className="flex flex-col gap-2">
              <div className="flex items-center justify-between px-2 py-1">
                <Text>应用版本</Text>
                <Text code>{sysConfig?.appVersion || '-'}</Text>
              </div>
              <div className="flex items-center justify-between px-2 py-1 border-t border-gray-100">
                <Text>MFA</Text>
                <Tag color={sysConfig?.bools?.['mfa.enabled'] ? 'success' : 'default'}>
                  {sysConfig?.bools?.['mfa.enabled'] ? '已启用' : '已禁用'}
                </Tag>
              </div>
              <div className="flex items-center justify-between px-2 py-1 border-t border-gray-100">
                <Text>SSL 证书</Text>
                <Tag color={sysConfig?.strings?.['ssl.domain'] ? 'success' : 'default'}>
                  {sysConfig?.strings?.['ssl.domain'] ? '已配置' : '未配置'}
                </Tag>
              </div>
            </div>
          </Card>
        </Col>
      </Row>

      {/* ── Quick links ────────────────────────────────────── */}
      <Card title={<><LinkOutlined className="mr-2" />快捷入口</>} size="small" className="mt-4">
        <Space wrap>
          {quickLinks.map((link) => (
            <Button key={link.path} icon={link.icon} onClick={() => navigate(link.path)}>
              {link.label}
            </Button>
          ))}
        </Space>
      </Card>
    </div>
  )
}

// frontend/src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <!-- Page header -->
    <PageHeader title="仪表盘">
      <template #actions>
        <el-button @click="loadAll" :loading="loading" size="small">
          <el-icon><Refresh /></el-icon> 刷新
        </el-button>
      </template>
    </PageHeader>

    <!-- Error alert -->
    <el-alert
      v-if="loadError"
      :title="loadError"
      type="error"
      show-icon
      :closable="true"
      @close="loadError = ''"
      style="margin-bottom: 20px"
    />

    <!-- Stat cards -->
    <div class="stat-grid">
      <StatusCard
        :value="stats.onlineCount"
        label="在线实例"
        :icon="Monitor"
        :sub="stats.instanceCount ? `/ ${stats.instanceCount}` : undefined"
        status="up"
        :status-text="onlineRateText"
        link="/instances"
      />
      <StatusCard
        :value="stats.tenantCount"
        label="租户数量"
        :icon="User"
        status="idle"
        status-text="已配置"
        link="/tenants"
      />
      <StatusCard
        :value="engine.runningTasks ?? 0"
        label="抢机引擎"
        :icon="SetUp"
        :sub="`/ ${engine.totalTasks ?? 0}`"
        :status="engineRunning ? 'up' : 'down'"
        :status-text="engineRunning ? '运行中' : '已停止'"
        link="/boot"
      />
    </div>

    <!-- Engine + Channels -->
    <div class="panel-grid">
      <!-- Notification channels -->
      <div class="panel">
        <div class="panel-header">
          <span class="panel-title">
            <el-icon :size="16"><Bell /></el-icon> 通知渠道
          </span>
        </div>
        <div class="panel-body">
          <div class="channel-list">
            <router-link v-for="ch in notificationChannels" :key="ch.name" to="/settings" class="channel-row channel-row--link">
              <div class="channel-left">
                <el-icon :size="16" :color="ch.enabled ? 'var(--status-up)' : 'var(--text-muted)'">
                  <ChatDotRound v-if="ch.name === 'Telegram'" />
                  <Message v-else-if="ch.name === 'DingTalk'" />
                  <Bell v-else-if="ch.name === 'Bark'" />
                  <Notification v-else />
                </el-icon>
                <span class="channel-name">{{ ch.label }}</span>
              </div>
              <span class="channel-state" :class="ch.enabled ? 'channel-state--up' : ''">
                {{ ch.enabled ? '已配置' : '未配置' }}
              </span>
            </router-link>
          </div>
        </div>
      </div>
    </div>

    <!-- Quick links + System overview -->
    <div class="panel-grid">
      <!-- Quick links -->
      <div class="panel">
        <div class="panel-header">
          <span class="panel-title">
            <el-icon :size="16"><Link /></el-icon> 快捷入口
          </span>
        </div>
        <div class="panel-body">
          <div class="quick-links">
            <router-link
              v-for="link in quickLinks"
              :key="link.path"
              :to="link.path"
              class="quick-link"
            >
              <el-icon :size="14"><component :is="link.icon" /></el-icon>
              {{ link.label }}
            </router-link>
          </div>
        </div>
      </div>

      <!-- System overview -->
      <div class="panel">
        <div class="panel-header">
          <span class="panel-title">
            <el-icon :size="16"><InfoFilled /></el-icon> 系统概览
          </span>
        </div>
        <div class="panel-body">
          <div class="info-list">
            <div class="info-row">
              <span class="info-label">应用版本</span>
              <span class="info-value data-mono">{{ appVersion || '-' }}</span>
            </div>
            <router-link to="/settings" class="info-row info-row--link">
              <span class="info-label">MFA</span>
              <span class="info-state" :class="mfaEnabled ? 'info-state--up' : ''">
                {{ mfaEnabled ? '已启用' : '已禁用' }}
                <el-icon :size="12" style="margin-left: 4px;"><ArrowRight /></el-icon>
              </span>
            </router-link>
            <div class="info-row">
              <span class="info-label">SSL 证书</span>
              <span class="info-state" :class="sslDomain ? 'info-state--up' : ''">
                {{ sslDomain ? '已配置' : '未配置' }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import {
  Refresh, Monitor, User,
  SetUp, Bell, Link, InfoFilled, ArrowRight,
  ChatDotRound, Message, Notification,
  Platform, Share, Setting, Promotion, VideoCamera, Warning
} from '@element-plus/icons-vue'
import PageHeader from '../components/common/PageHeader.vue'
import StatusCard from '../components/common/StatusCard.vue'
import request from '../utils/request'
import type { DashboardStats, EngineStatus, MessageChannels, SystemConfig } from '../types/api'

const loading = ref(false)
const loadError = ref('')

const stats = ref<DashboardStats>({
  tenantCount: 0, proxyCount: 0, instanceCount: 0, backupCount: 0, onlineCount: 0,
})
const engine = ref({
  parentActive: 0,
  apiActive: 0,
  parentCapacity: 0,
  apiCapacity: 0,
  registeredJobs: 0,
  totalTasks: 0,
  runningTasks: 0,
})
const notificationChannels = ref<Array<{ name: string; label: string; enabled: boolean }>>([])

const appVersion = ref('')
const mfaEnabled = ref(false)
const sslDomain = ref('')

const engineRunning = computed(() => {
  return engine.value.parentActive > 0 || engine.value.registeredJobs > 0
})

const onlineRateText = computed(() => {
  if (stats.value.instanceCount) {
    return `${Math.round((stats.value.onlineCount / stats.value.instanceCount) * 100)}% 在线率`
  }
  return '暂无数据'
})

const quickLinks = [
  { label: '抢机任务', path: '/boot', icon: Platform },
  { label: '实例列表', path: '/instances', icon: Monitor },
  { label: 'SSH 终端', path: '/terminal', icon: Promotion },
  { label: '系统设置', path: '/settings', icon: Setting },
  { label: 'VNC 控制台', path: '/console', icon: VideoCamera },
  { label: '救援模式', path: '/rescue', icon: Warning },
]

async function loadAll() {
  loading.value = true
  loadError.value = ''
  try {
    await Promise.all([
      loadStats(),
      loadEngine(),
      loadNotifications(),
      loadSystemInfo(),
    ])
  } catch {
    // individual load functions handle errors
  }
  loading.value = false
}

async function loadStats() {
  try {
    const data: DashboardStats = await request.get('/api/stats')
    if (data) stats.value = data
  } catch (e: any) {
    if (!loadError.value) loadError.value = '加载统计数据失败: ' + (e.message || '未知错误')
  }
}

async function loadEngine() {
  try {
    const data: EngineStatus = await request.get('/boot/systemStatus')
    if (data) {
      engine.value = {
        parentActive: data.parentActive || 0,
        apiActive: data.apiActive || 0,
        parentCapacity: data.parentCapacity || 0,
        apiCapacity: data.apiCapacity || 0,
        registeredJobs: data.registeredJobs || 0,
        totalTasks: data.totalTasks || 0,
        runningTasks: data.runningTasks || 0,
      }
    }
  } catch { /* engine may not be available */ }
}

async function loadNotifications() {
  try {
    const data: MessageChannels = await request.get('/api/config/message-enabled')
    if (data) {
      notificationChannels.value = [
        { name: 'Telegram', label: 'Telegram', enabled: data.telegram },
        { name: 'DingTalk', label: '钉钉', enabled: data.dingtalk },
        { name: 'Bark', label: 'Bark', enabled: data.bark },
        { name: 'Feishu', label: '飞书', enabled: data.feishu },
      ]
    }
  } catch { /* optional */ }
}

async function loadSystemInfo() {
  try {
    const data: SystemConfig = await request.get('/system/config')
    if (data) {
      appVersion.value = data.appVersion || ''
      mfaEnabled.value = data.bools?.['mfa.enabled'] || false
      sslDomain.value = data.strings?.['ssl.domain'] || ''
    }
  } catch { /* optional */ }
}

onMounted(loadAll)
</script>

<style scoped>
.dashboard {
  max-width: 1200px;
}

/* ============================================================
   Stat Grid
   ============================================================ */

.stat-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-4);
  margin-bottom: var(--space-6);
}

/* ============================================================
   Panel Grid (2-col)
   ============================================================ */

.panel-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-4);
  margin-bottom: var(--space-4);
}

@media (max-width: 768px) {
  .panel-grid {
    grid-template-columns: 1fr;
  }
}

/* ============================================================
   Panel (card)
   ============================================================ */

.panel {
  background: var(--bg-surface);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
  overflow: hidden;
}

.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--space-3) var(--space-5);
  border-bottom: 1px solid var(--border-subtle);
}

.panel-title {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--text-sm);
  font-weight: var(--font-semibold);
  color: var(--text-primary);
}

.panel-title :deep(.el-icon) {
  color: var(--text-muted);
}

.panel-body {
  padding: var(--space-4) var(--space-5);
}

/* ============================================================
   Engine
   ============================================================ */

/* ============================================================
   Notification Channels
   ============================================================ */

.channel-list {
  display: flex;
  flex-direction: column;
  gap: 1px;
}

.channel-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--space-2) var(--space-3);
  border-radius: var(--radius-sm);
  transition: background var(--transition-fast);
}

.channel-row:hover {
  background: var(--bg-raised);
}

.channel-left {
  display: flex;
  align-items: center;
  gap: var(--space-3);
}

.channel-name {
  font-size: var(--text-sm);
  color: var(--text-primary);
  font-weight: var(--font-medium);
}

.channel-state {
  font-size: var(--text-xs);
  color: var(--text-muted);
  font-weight: var(--font-medium);
}

.channel-state--up {
  color: var(--status-up);
}

.channel-row--link {
  text-decoration: none;
  color: inherit;
  cursor: pointer;
}

.channel-row--link:hover {
  background: var(--bg-hover);
}

/* ============================================================
   Quick Links
   ============================================================ */

.quick-links {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-2);
}

@media (max-width: 480px) {
  .quick-links {
    grid-template-columns: 1fr;
  }
}

.quick-link {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-2) var(--space-3);
  border-radius: var(--radius-sm);
  font-size: var(--text-sm);
  font-weight: var(--font-medium);
  color: var(--text-secondary);
  text-decoration: none;
  transition: background var(--transition-fast), color var(--transition-fast);
}

.quick-link:hover {
  background: var(--bg-raised);
  color: var(--accent);
}

/* ============================================================
   System Info
   ============================================================ */

.info-list {
  display: flex;
  flex-direction: column;
}

.info-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--space-2) 0;
}

.info-row--link {
  text-decoration: none;
  color: inherit;
  cursor: pointer;
  border-radius: var(--radius-sm);
  transition: background var(--transition-fast);
  padding-left: var(--space-1);
  padding-right: var(--space-1);
  margin: 0 calc(var(--space-1) * -1);
}

.info-row--link:hover {
  background: var(--bg-hover);
}

.info-row + .info-row {
  border-top: 1px solid var(--border-subtle);
}

.info-label {
  font-size: var(--text-sm);
  color: var(--text-secondary);
  font-weight: var(--font-medium);
}

.info-value {
  font-size: var(--text-sm);
  color: var(--text-primary);
  font-weight: var(--font-medium);
}

.info-state {
  font-size: var(--text-xs);
  color: var(--text-muted);
  font-weight: var(--font-medium);
}

.info-state--up {
  color: var(--status-up);
}

/* ============================================================
   Responsive
   ============================================================ */

@media (max-width: 768px) {
  .stat-grid {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 480px) {
  .stat-grid {
    grid-template-columns: 1fr;
  }
}
</style>
