// frontend/src/pages/vnic/modals/AddRuleModal.tsx
import { useState } from 'react'
import { Modal, Form, Select, Input, Radio, message } from 'antd'
import { vnicAddSecurityRule } from '@/api/vnic'

interface Props {
  open: boolean
  onClose: () => void
  tenantId: number
  onSuccess: () => void
}

export default function AddRuleModal({ open, onClose, tenantId, onSuccess }: Props) {
  const [saving, setSaving] = useState(false)
  const [form] = Form.useForm()

  const protocol = Form.useWatch('protocol', form) || 'all'
  const ruleType = Form.useWatch('type', form) || 'ingress'

  async function handleAdd(values: { type: string; protocol: string; source: string; ports?: string; icmpType?: string }) {
    setSaving(true)
    try {
      await vnicAddSecurityRule({
        tenantId,
        type: values.type,
        protocol: values.protocol,
        source: values.source,
        ports: values.ports || undefined,
        icmpType: values.protocol === 'icmp' ? values.icmpType : undefined,
      })
      message.success('规则添加成功')
      onSuccess()
      onClose()
      form.resetFields()
    } catch (e: unknown) {
      message.error((e as Error).message || '规则添加失败')
    } finally {
      setSaving(false)
    }
  }

  return (
    <Modal open={open} title="添加安全规则" onCancel={onClose} onOk={() => form.submit()} confirmLoading={saving} destroyOnClose>
      <Form form={form} layout="vertical" onFinish={handleAdd} initialValues={{ type: 'ingress', protocol: 'all', source: '0.0.0.0/0' }}>
        <Form.Item name="type" label="类型">
          <Radio.Group options={[
            { label: '入站', value: 'ingress' },
            { label: '出站', value: 'egress' },
          ]} />
        </Form.Item>
        <Form.Item name="protocol" label="协议">
          <Select options={[
            { label: '全部 (all)', value: 'all' },
            { label: 'TCP', value: 'tcp' },
            { label: 'UDP', value: 'udp' },
            { label: 'ICMP', value: 'icmp' },
          ]} />
        </Form.Item>
        <Form.Item name="source" label={ruleType === 'ingress' ? '源 CIDR' : '目标 CIDR'}>
          <Input placeholder="0.0.0.0/0" />
        </Form.Item>
        {(protocol === 'tcp' || protocol === 'udp') && (
          <Form.Item name="ports" label="端口">
            <Input placeholder="80 或 8080-9090" />
          </Form.Item>
        )}
        {protocol === 'icmp' && (
          <Form.Item name="icmpType" label="ICMP Type">
            <Input placeholder="8, 0" />
          </Form.Item>
        )}
      </Form>
    </Modal>
  )
}

// frontend/src/components/vnic/AddRuleModal.vue
<script setup lang="ts">
defineOptions({ name: 'AddRuleModal' })

import { ref, computed } from 'vue'
import { ElMessage } from 'element-plus'
import request from '../../utils/request'

const props = defineProps<{ modelValue: boolean; tenantId: number }>()
const emit = defineEmits<{ 'update:modelValue': [val: boolean]; saved: [] }>()

const saving = ref(false)
const form = ref({
  type: 'ingress' as 'ingress' | 'egress',
  protocol: 'all',
  source: '0.0.0.0/0',
  ports: '',
  icmpType: '8, 0',
})

const showPorts = computed(() => form.value.protocol === 'tcp' || form.value.protocol === 'udp')
const showIcmp = computed(() => form.value.protocol === 'icmp')

async function handleAdd() {
  saving.value = true
  try {
    await request.post('/tenants/security-rules', {
      tenantId: props.tenantId,
      type: form.value.type,
      protocol: form.value.protocol,
      source: form.value.source,
      ports: form.value.ports || undefined,
      icmpType: showIcmp.value ? form.value.icmpType : undefined,
    })
    ElMessage.success('规则添加成功')
    emit('saved')
    emit('update:modelValue', false)
  } catch (e: any) {
    ElMessage.error(e.message || '规则添加失败')
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <el-dialog :model-value="modelValue" @update:model-value="emit('update:modelValue', $event)" title="添加安全规则" width="520px" destroy-on-close>
    <el-form :model="form" label-width="100px">
      <el-form-item label="类型">
        <el-radio-group v-model="form.type">
          <el-radio value="ingress">入站</el-radio>
          <el-radio value="egress">出站</el-radio>
        </el-radio-group>
      </el-form-item>
      <el-form-item label="协议">
        <el-select v-model="form.protocol" style="width: 100%;">
          <el-option label="全部 (all)" value="all" />
          <el-option label="TCP" value="tcp" />
          <el-option label="UDP" value="udp" />
          <el-option label="ICMP" value="icmp" />
        </el-select>
      </el-form-item>
      <el-form-item :label="form.type === 'ingress' ? '源 CIDR' : '目标 CIDR'">
        <el-input v-model="form.source" placeholder="0.0.0.0/0" />
      </el-form-item>
      <el-form-item v-if="showPorts" label="端口">
        <el-input v-model="form.ports" placeholder="80 或 8080-9090" />
      </el-form-item>
      <el-form-item v-if="showIcmp" label="ICMP Type">
        <el-input v-model="form.icmpType" placeholder="8, 0" />
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="emit('update:modelValue', false)">取消</el-button>
      <el-button type="primary" :loading="saving" @click="handleAdd">添加</el-button>
    </template>
  </el-dialog>
</template>
